In [0]:
import numpy as np

**Basic operations**

In [0]:
a = np.array([1,2,3], dtype = 'int16') #by default numpy takes int32 i.e. 4 bytes of space for storing int. 

In [0]:
b = np.array([[1,2,3],
             [4,5,6]])

In [0]:
print(b)

[[1 2 3]
 [4 5 6]]


In [0]:
a.ndim

1

In [0]:
b.ndim

2

In [0]:
a.shape #one dimensional array with three elements

(3,)

In [0]:
b.shape

(2, 3)

In [0]:
a.dtype #a.datatype not a.type

dtype('int16')

In [0]:
a.itemsize #to see how many bytes are occupied by one element

2

In [0]:
b.itemsize

8

In [0]:
b.dtype #two dimensional array

dtype('int64')

In [0]:
a.size #total number of elements

3

In [0]:
b.size

6

In [0]:
#get total byte size occupied in memory
a.size * a.itemsize

6

In [0]:
#or
a.nbytes

6

In [0]:
b.nbytes

48

**Accessing/ Changing specific elements, rows, columns....**

In [0]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [0]:
print (a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [0]:
a.shape

(2, 7)

In [0]:
#get a specific element [row, col]
print(a[1,5])

13


In [0]:
#negative second element in second row
print(a[1,-2])

13


In [0]:
#get a specific row
print(a[1,:]) #all columns in second row

[ 8  9 10 11 12 13 14]


In [0]:
#get a specific column
print(a[:, 5]) #all rows in 6th column

[ 6 13]


In [0]:
#getting more customizes [startindex:endindex:stepsize] ===>> in row or column
print(a[0,1:5:2]) #print 2 to 5 by skipping two elements in row 0

[2 4]


In [0]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [0]:
print(a[0,1:-1:2]) #get 2,4,6

[2 4 6]


In [0]:
#change elements
a[1,5] = 20

In [0]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [0]:
#change all rows in third column to be 3
a[:,2] = 3

In [0]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9  3 11 12 20 14]]


In [0]:
#3D array
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [0]:
print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [0]:
# for accessing work outside in
print(a[0,1,1]) #get 4

4


In [0]:
#get the first 2-d array
print(a[:,1,:]) #all array, 2nd row, all elements in row

[[3 4]
 [7 8]]


In [0]:
print(a[1,1,0])

7


In [0]:
#replace
a[:,1, :] = [[2, 2],[33,3]]

In [0]:
print(a)

[[[ 1  2]
  [ 2  2]]

 [[ 5  6]
  [33  3]]]


**Initializing different types of array**

In [0]:
#all zeros
a = np.zeros((2,3,3))

In [0]:
print(a)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [0]:
#all ones
a = np.ones((2,3), dtype = 'int8')

In [0]:
print (a)

[[1 1 1]
 [1 1 1]]


In [0]:
print(a.itemsize)

1


In [0]:
print(a.size * a.itemsize)

6


In [0]:
#any other number
a = np.full((2,2),100, dtype = 'float16')

In [0]:
print(a)

[[100. 100.]
 [100. 100.]]


In [0]:
#any other number
a = np.full_like(a, 4) 

In [0]:
print(a)

[[4. 4.]
 [4. 4.]]


In [0]:
print(np.full(a.shape, 4))

[[4 4]
 [4 4]]


In [0]:
#initializing array with random numbers
print(np.random.randn(2,4)) #np.random.randn is for Standard Normal (aka. Gaussian) distribution (mean 0 and variance 1)

[[1.44245455 1.05459481 1.69110554 0.15072357]
 [0.75857053 0.75690246 0.60918967 0.32141597]]


In [0]:
print(np.random.randn(2,4,3)) #in bracket it is the shape

[[[-0.6287488  -0.34343971  1.69339387]
  [ 1.27167937 -0.47486554  0.87974788]
  [-0.03522907  0.82477833 -0.43953061]
  [-1.3279903  -0.23142377 -0.10225054]]

 [[-0.67364461  0.88721609  1.31947469]
  [ 0.79645309  0.80890577  1.25811953]
  [ 1.46182606 -0.43283066 -0.65509416]
  [ 0.5679541  -0.83837015 -0.33376197]]]


In [0]:
print(a.shape)

(2, 2)


In [0]:
print(np.random.random_sample(a.shape))

[[0.29679046 0.84851735]
 [0.24918877 0.80573764]]


In [0]:
print(np.random.rand(4,2)) #np.random.rand is for Uniform distribution in the half-open interval [0.0, 1.0)

[[0.31798835 0.34779911]
 [0.23881675 0.67609367]
 [0.94243897 0.42745297]
 [0.04668907 0.82253381]]


In [0]:
#random integer values
print(np.random.randint(5)) #will generate from 0 to 4 (exclusive 5)

4


In [0]:
print(np.random.randint(0, 10)) #generates random number between 0 to 9 (exclusive 10)

4


In [0]:
print(np.random.randint(0, 10, size = (3,3)))

[[1 7 0]
 [6 5 3]
 [0 6 9]]
None


In [0]:
print(np.random.randint(-5, 10, size = (3,3)))

[[-4  8  7]
 [ 5  7  2]
 [ 5  6 -2]]


In [0]:
#identity matrix
print(np.identity(5)) #identity matrix of 5,5

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [0]:
#repeat an array n times
n=3
arr = np.array([1,2,3])
print(arr.repeat(n))

[1 1 1 2 2 2 3 3 3]


In [0]:
#repeat along an aixs
arr = np.array([[1,2,3]]) #two brackets at end = 2d array
print(arr.repeat(n, axis = 0)) #repeat along rows

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [0]:
print(np.repeat(arr,n,axis=0)) #same as above but prefer this

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [0]:
print(np.repeat(arr,n,axis=1)) #repeat along columns

[[1 1 1 2 2 2 3 3 3]]


In [0]:
a = np.full((5,5),1)

In [0]:
a

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [0]:
a[1:4:1,1] =0

In [0]:
a

array([[1, 1, 1, 1, 1],
       [1, 0, 1, 1, 1],
       [1, 0, 1, 1, 1],
       [1, 0, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [0]:
a[1:4:1,-2] =0

In [0]:
a

array([[1, 1, 1, 1, 1],
       [1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1],
       [1, 1, 1, 1, 1]])

In [0]:
a[2,2] = 9

In [0]:
a

array([[1, 1, 1, 1, 1],
       [1, 0, 1, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 1, 0, 1],
       [1, 1, 1, 1, 1]])

In [0]:
#or
a = np.ones((5,5))
z = np.zeros((3,3))

In [0]:
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [0]:
z[1,1] =9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [0]:
a[1:4,1:4] = z #by default stepsize is 1
# same as a[1:-1, 1:-1] #-1 is exclusive

In [0]:
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Be careful while copying arrays!

In [0]:
a = np.array([1,2,3])
b = a #any change in b will reflect in a. b is points to the same as a
b[0] = 100
print(a)

[100   2   3]


In [0]:
# to avoid thi create a copy
c = a.copy()

In [0]:
c[1] = 200
print(a) #a remains same

[100   2   3]


**mathematics**

In [0]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [0]:
#element wise operations ===> this wont change the original array
a+2

array([5, 6, 7])

In [0]:
a - 2

array([1, 2, 3])

In [0]:
a / 2

array([1.5, 2. , 2.5])

In [0]:
a +=2 #will change the content of a

In [0]:
a 

array([5, 6, 7])

In [0]:
b = np.array([2,5,6])
a + b

array([ 7, 11, 13])

In [0]:
a ** 2

array([25, 36, 49])

In [0]:
#take sine of all values
np.sin(a)

array([-0.95892427, -0.2794155 ,  0.6569866 ])

In [0]:
np.tan(a)

array([-3.38051501, -0.29100619,  0.87144798])

**Linear Algebra**

In [0]:
a = np.ones((2,3))

In [0]:
b = np.full((3,4), 5)

In [0]:
#for doing product no. of cols of 1st one = no. of rows of 2nd one
print(a)
print(b)
print(np.matmul(a,b)) #matrix multiplication


[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[15. 15. 15. 15.]
 [15. 15. 15. 15.]]


In [0]:
print(np.matmul(a,b).shape)

(2, 4)


In [0]:
#find determinant of matrix
a = np.identity(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [0]:
print(np.linalg.det(a))

1.0


In [0]:
###Statistics

In [0]:
s = np.array([1,2,3])

In [0]:
print(np.min(s)) #minimum

1


In [0]:
print(np.max(s)) #maximum

3


In [0]:
print(np.min(s, axis = 0))

1


In [0]:
print(np.max(s, axis = 0))

3


In [0]:
s = np.array([[1,2,3],[4,5,6]])

In [0]:
print(np.min(s, axis = 1))

[1 4]


In [0]:
s

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
print(np.sum(s)) # sum of all elements

21


In [0]:
print(np.sum(s, axis = 0)) # each column values will be added

[5 7 9]


In [0]:
print(np.sum(s, axis = 1)) #sum of all elements in a row

[ 6 15]


**Reorganizing Arrays**

In [0]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2)) #product of all dimensions should remain same i.e. number of elements
print(after)



[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [0]:
print(before.reshape(2,2,2,1))

[[[[1]
   [2]]

  [[3]
   [4]]]


 [[[5]
   [6]]

  [[7]
   [8]]]]


In [0]:
#vertically stacking arrays
v1 = np.array([[1,2,3],[4,5,6]])
v2 = np.array([[7,8,9],[10,11,12]])

#size of v1,v2 should be same
print(np.vstack([v1,v2])) #WHILE CREATING ANY ARRAY [] IS REQUIRED 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [0]:
print(np.vstack([v1,v2,v2,v1])) #size

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [ 7  8  9]
 [10 11 12]
 [ 1  2  3]
 [ 4  5  6]]


In [0]:
#horizontal stacking
h1 = np.array([1,2,3])
h2 = np.array([4,5,6])

In [0]:
print(np.hstack([h1,h2])) #size should be same

[1 2 3 4 5 6]


In [0]:
#difference between resize and reshape
a = np.array([[1,2,3],[4,5,6]])
b = a.reshape((3,2))
print(a)
print(b)
c = a.resize((6,1))
print(a) #original array doesnt change after reshape but resize will affect the shape of the array

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
